### PR TITLE
new welcome page text

### PR DESCRIPTION
**Pull request by Phoenix1747**
Hi,

I edited the welcome page text, as arranged. :)

### CODE REVIEW

**Comment by EliasS87** [comment]
Hey

Cool. I merged it. I have been pretty busy lately but ill try and work on
the last six pages, plus that email form on the Support page.

**Comment by Phoenix1747** [comment]
Alright cool, but I don't see anything on the support page. What do you mean with email form?

**Comment by EliasS87** [comment]
On your old site, there was a submit an email form there where users could shoot you a message. Do you still want that or just an email address?

**Comment by Phoenix1747** [comment]
Yeah, I still want that. But you said you worked on the form? You didn't push it yet, did you?

**Comment by EliasS87** [comment]
No I have not. I just started a job so I am pressed for time.

**Comment by Phoenix1747** [comment]
Ok I get it. No problem, take your time! I was just curious :smiley:

**Comment by EliasS87** [comment]
Np man. I'd like to get it done real soon. As soon as I get into the swing
of things at work it will be back on the front burner so to speak.

**Pull request merged**
